name: ipsum
description: A simple lorem ipsum text generator for dart based off of the lipsum library for Python.
version: 1.0.1
homepage: https://github.com/dominic-schmid/ipsum

environment:
  sdk: ">=2.18.2 <3.0.0"
