name: ipsum
description: A simple lorem ipsum text generator for dart based off of the lipsum library for Python.
authors:
  - Dominic Schmid <dominic.schmid@hotmail.com>
version: 1.0.0
homepage: https://github.com/dominic-schmid/ipsum

environment:
  sdk: ">=2.18.2 <3.0.0"
